FROM python

ENV PYTHONUNBUFFERED 1

ARG DAPHNE_WORKERS
ENV DAPHNE_WORKERS ${GUNICORN_WORKERS:-3}

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "chatApp.asgi:application"]
