services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "${ZOOKEEPER_PORT}:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "${KAFKA_PORT}:9092"
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - DAPHNE_WORKERS=${DAPHNE_WORKERS}
    environment:
      DJANGO_SETTINGS_MODULE: chatApp.settings
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "chatApp.asgi:application"]
    volumes:
      - .:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
      - kafka
      - zookeeper

  kafka_consumer:
    build:
      context: .
      dockerfile: Dockerfile.kafka
    environment:
      - KAFKA_BROKER=kafka_temp:9092
      - DJANGO_SETTINGS_MODULE=chatApp.settings
    command: [ "python", "manage.py", "run_consumers" ]
    volumes:
      - .:/app
    depends_on:
      - kafka
      - web

volumes:
  postgres_data: